// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANpx-FR73eQ25oSrA9ze6VW-sy1jgtilI',
    appId: '1:544591359171:web:15a1e5c25b128f3520c676',
    messagingSenderId: '544591359171',
    projectId: 'drc-gov-track',
    authDomain: 'drc-gov-track.firebaseapp.com',
    storageBucket: 'drc-gov-track.firebasestorage.app',
    measurementId: 'G-7JQ76CREMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4TPibbjH8qZYA-huNXehgp4jLWKN7oIw',
    appId: '1:544591359171:android:ff59a54e70821b4e20c676',
    messagingSenderId: '544591359171',
    projectId: 'drc-gov-track',
    storageBucket: 'drc-gov-track.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxoG6-OFdQ8S8Wv43s89XcLI9ESC5CEI',
    appId: '1:544591359171:ios:dcd42dcf5ef16a2920c676',
    messagingSenderId: '544591359171',
    projectId: 'drc-gov-track',
    storageBucket: 'drc-gov-track.firebasestorage.app',
    iosBundleId: 'com.example.drcGovTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYxoG6-OFdQ8S8Wv43s89XcLI9ESC5CEI',
    appId: '1:544591359171:ios:dcd42dcf5ef16a2920c676',
    messagingSenderId: '544591359171',
    projectId: 'drc-gov-track',
    storageBucket: 'drc-gov-track.firebasestorage.app',
    iosBundleId: 'com.example.drcGovTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANpx-FR73eQ25oSrA9ze6VW-sy1jgtilI',
    appId: '1:544591359171:web:d5487f3d8a4de3bd20c676',
    messagingSenderId: '544591359171',
    projectId: 'drc-gov-track',
    authDomain: 'drc-gov-track.firebaseapp.com',
    storageBucket: 'drc-gov-track.firebasestorage.app',
    measurementId: 'G-ZY5QWEQ7YG',
  );
}
